[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/ph/static/*"
  to = "https://eu-assets.i.posthog.com/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ph/*"
  to = "https://eu.i.posthog.com/:splat"
  status = 200
  force = true
